precision highp float ;
uniform vec4 u_ambient ;
uniform sampler2D u_diffuse ;
uniform vec4 u_emission ;
varying vec3 v_normal ;
varying vec3 v_position ;
uniform vec4 u_reflective ;
uniform float u_reflectivity ;
uniform float u_shininess ;
uniform vec4 u_specular ;
varying vec2 v_texcoord0 ;
uniform float u_transparency ;
uniform vec4 u_transparent ;
void main (void) {
vec3 normal =normalize (v_normal) ;
vec4 color =vec4(0., 0., 0., 0.) ;
vec4 diffuse =vec4(0., 0., 0., 1.) ;
vec4 emission ;
vec4 reflective ;
vec4 ambient ;
vec4 specular ;
ambient =u_ambient ;
diffuse =texture2D (u_diffuse, v_texcoord0) ;
emission =u_emission ;
reflective =u_reflective ;
specular =u_specular ;
diffuse.xyz +=reflective.xyz ;
diffuse.xyz *=max (dot (normal, vec3(0., 0., 1.)), 0.) ;
color.xyz +=diffuse.xyz ;
color.xyz +=emission.xyz ;
color =vec4(color.rgb * diffuse.a, diffuse.a * u_transparency) ;
gl_FragColor =color ;
}
